;;;;;;;;;; 包加载入口 ;;;;;;;;;;
;; 更好的默认设置
(require 'init-better-default)
;; 加载company-mode的自定义配置
(require 'init-company-mode)
;; 加载dired模式的自定义配置
(require 'init-dired)
;; helm插件配置
(require 'init-helm)
;; 写代码中-英文翻译辅助插件
(require 'init-insert-translated-name)
;; 按键绑定
(require 'init-key-binding)
;; 自定义函数
(require 'init-my-function)
;; 网络配置
(require 'init-network)
;; org-mode配置
(require 'init-org-mode)
;; org-pomodoro插件配置
(require 'init-org-pomodoro)
;; 加载包
(require 'init-package)
;; 快速访问按键配置
(require 'init-quick-access)
;; 主题设置
(require 'init-theme)
;; 界面外观设置
(require 'init-ui)
;; virtualenvwrapper虚拟化环境配置
(require 'init-virtualenvwrapper)
;; 滚动另一个窗口插件配置
(require 'init-watch-other-window)
;; 有道词典配置
(require 'init-youdao-dictionary)

;; 提供init-config模块
(provide 'init-config)
